describe("ruby-lsp.health", function()
	describe("Checking for required plugins", function()
		describe("when a plugin is missing", function()
			it("says not found", function() end)
		end)
		describe("when a plugin is present", function()
			it("confirms installation", function() end)
		end)
	end)
	describe("Checking for external dependencies", function()
		describe("when a dependency is missing", function()
			it("says not found", function() end)
		end)
		describe("when a dependency is present", function()
			it("lists name, version, and location", function() end)
		end)
	end)
	describe("Checking for configured linters", function()
		describe("when a config is present", function()
			describe("and the linter is present", function()
				it("lists name, version, and location", function() end)
			end)
			describe("but the linter is not present", function()
				it("say config found, linter not found", function() end)
			end)
		end)
	end)
end)
